### PR TITLE
Remove lmspmd2b and lmtransformeradam nightly runs

### PR DESCRIPTION
**Pull request by RissyRan**
# Description

Remove lmspmd2b and lmtransformeradam nightly runs, as those tests have been running on [Airflow](https://screenshot.googleplex.com/sEfU4xBMks4XGzB). Failed with the same reason.

# Tests

Please describe the tests that you ran on TPUs to verify changes.

**Instruction and/or command lines to reproduce your tests:** ...

Run `./scripts/gen-tests.sh`

**List links for your tests (use go/shortn-gen for any internal link):** ...

Check schedule of the test has been updated, one example [here](https://screenshot.googleplex.com/8EL3FQqQJUUByw4).

# Checklist

Before submitting this PR, please make sure (put X in square brackets):
- [x] I have performed a self-review of my code.
- [x] I have necessary comments in my code, particularly in hard-to-understand areas.
- [x] I have run one-shot tests and provided workload links above if applicable. 
- [x] I have made or will make corresponding changes to the doc if needed.

### CODE REVIEW

**Comment by RissyRan** [comment]
> Clever detail to assign scheduling date to Feb 31st haha. Is there a reason we don't outright delete these tests since they are now running on Airflow?

Thanks! Good question. Not like a few tests that are directly imported form Jsonnet in this repo to Airflow (i.e. JAX API and PT tests), Pax tests are safe to delete as we implement it from scratch. So removal works too! I guess the main reason I disable them instead of deletion is to keep them as example for you to onboard the rest 2 tests. I don't have preference. I am happy to remove it in this PR if you prefer.

**Comment by gkroiz** [comment]
> > Clever detail to assign scheduling date to Feb 31st haha. Is there a reason we don't outright delete these tests since they are now running on Airflow?
> 
> Thanks! Good question. Not like a few tests that are directly imported form Jsonnet in this repo to Airflow (i.e. JAX API and PT tests), Pax tests are safe to delete as we implement it from scratch. So removal works too! I guess the main reason I disable them instead of deletion is to keep them as example for you to onboard the rest 2 tests. I don't have preference. I am happy to remove it in this PR if you prefer.

Let's remove, I can reference older commits of this repository when onboarding the other Pax models.

**Comment by RissyRan** [comment]
> > > Clever detail to assign scheduling date to Feb 31st haha. Is there a reason we don't outright delete these tests since they are now running on Airflow?
> > 
> > 
> > Thanks! Good question. Not like a few tests that are directly imported form Jsonnet in this repo to Airflow (i.e. JAX API and PT tests), Pax tests are safe to delete as we implement it from scratch. So removal works too! I guess the main reason I disable them instead of deletion is to keep them as example for you to onboard the rest 2 tests. I don't have preference. I am happy to remove it in this PR if you prefer.
> 
> Let's remove, I can reference older commits of this repository when onboarding the other Pax models.

Sounds good. Will do in a min.

**Review by gkroiz — APPROVED** [review]
LGTM

**Pull request merged**
