### PR TITLE
Verify fairseq-generate being installed

### PR DESCRIPTION
**Pull request by JackCaoG**
For some reason `fairseq-generate` is not available after `fairseq` installation. I was not able to repo locally on the xlml test docker. Adding this and manually trigger the test to help the debug.

error is `/bin/bash: line 46: fairseq-generate: command not found` after 25 epoches of training is completed.

### CODE REVIEW

**Comment by will-cromar** [comment]
It's currently the TPU VM version of this test that is hitting the error, which does not use the docker image. To reproduce, you can try running these setup steps on TPU VM and figure out why `fairseq-generate` is not on the PATH:

https://github.com/GoogleCloudPlatform/ml-testing-accelerators/blob/4bb7bdf01de7c631ccc983efd0f843138346c7b1/k8s/us-central1/gen/pt-nightly-fs-transformer-conv-v3-8-1vm.yaml#L135

**Comment by JackCaoG** [comment]
Ah, I didn't know TPUVM does not use docker.

**Comment by JackCaoG** [comment]
I verified that `sudo pip install` solved the issue, it is a permission thing.

**Review by will-cromar — APPROVED** [review]

**Comment by JackCaoG** [comment]
Unless we will run this test in the TPUVM docker, I think using `sudo` should be fine

**Pull request merged**
