### PR TITLE
Remove language model tests.

### PR DESCRIPTION
**Pull request by vanbasten23**
# Description

Per discussion, this PR deletes language model test because they are not relevant anymore.

# Tests

Please describe the tests that you ran on TPUs to verify changes.

**Instruction and/or command lines to reproduce your tests:** : na

**List links for your tests (use go/shortn-gen for any internal link):** : na

# Checklist

Before submitting this PR, please make sure (put X in square brackets):
- [x] I have performed a self-review of my code.
- [x] I have necessary comments in my code, particularly in hard-to-understand areas.
- [x] I have run one-shot tests and provided workload links above if applicable. 
- [x] I have made or will make corresponding changes to the doc if needed.

### CODE REVIEW

**Comment by JackCaoG** [comment]
we actually want to keep vit I think

**Comment by vanbasten23** [comment]
> we actually want to keep vit I think

Ok, let me update my pr.

**Comment by vanbasten23** [comment]
> > we actually want to keep vit I think
> 
> Ok, let me update my pr.

Done.

**Review by will-cromar — APPROVED** [review]
Thanks!

**Comment by vanbasten23** [comment]
Thanks for the review!

**Pull request merged**
