### PR TITLE
Moving TF-2.4.0 tests to TF-2.4.1 for Patch release regression.

### PR DESCRIPTION
**Pull request by aman2930**

### CODE REVIEW

**Comment by will-cromar** [comment]
Do you want to add the dashboard tab in this PR as well?

**Comment by aman2930** [comment]
Added the dashboard.

**Review by will-cromar — APPROVED** [review]
LGTM

**Comment by jysohn23** [comment]
Seems like this didn't run `./scripts/gen-tests.sh`? At master head, if you run that script it's picking up all those changes.

**Comment by jysohn23** [comment]
> Seems like this didn't run `./scripts/gen-tests.sh`? At master head, if you run that script it's picking up all those changes.

Just chatted w/ @zcain117 looks like we now have postsubmit run the above and yamls are no longer accurate on master HEAD.

**Pull request merged**
