### PR TITLE
Overwrite cache when running HF tests

### PR DESCRIPTION
**Pull request by jysohn23**

### CODE REVIEW

**Comment by jysohn23** [comment]
Actually not quite, let me correct myself. This should just be a safeguard but not really change much in terms of behavior.

**Comment by zcain117** [comment]
> Actually not quite, let me correct myself. This should just be a safeguard but not really change much in terms of behavior.

I see - so maybe it's just good practice to overwrite the cache to avoid spurious test failures? But in this case it won't fix the underlying problem of why the test is failing?

**Comment by jysohn23** [comment]
Yes, this is orthogonal to the root cause fix.

**Comment by zcain117** [comment]
Adding this flag in #101 since the generated files in this PR are out of date now

**Pull request closed without merging**
