### PR TITLE
Add LLaMA2 model to pt nightly tests

### PR DESCRIPTION
**Pull request by ManfeiBai**
# Description

Add LLaMA2 model to xl-ml-dashboard to track

# Tests

./scripts/run-oneshot.sh -t pt-nightly-l2-n-i-func-v4-8-1vm
./scripts/run-oneshot.sh -t pt-nightly-l2-t-h-f-func-v4-8-1vm

(`l2` means `llama2`, `-e` means `-eager`, `-c` means `-chat`, `-t` means `-tocken`, `-q` means `-quantization`, `-w` means `-without-download`, `-n-i` means `-next-inference`, `-s` means `-stable`, `-xla` means `-xla`)

# Checklist

Before submitting this PR, please make sure (put X in square brackets):
- [X] I have performed a self-review of my code.
- [X] I have necessary comments in my code, particularly in hard-to-understand areas.
- [X] I have run one-shot tests and provided workload links above if applicable. 
- [X] I have made or will make corresponding changes to the doc if needed.

### CODE REVIEW

**Comment by miladm** [comment]
@ManfeiBai wdyt we submit a follow up PR for GPU testing as well? (after this work successfully lands)

**Comment by ManfeiBai** [comment]
> We need a metric to detect regressions. For inference, we can define a `latency/token` threshold that we know is reachable. For training, we can define a MFU threshold.
> 
> Let's use our benchmark results to define the right threshold values. Wdyt?

For metric to detect regression, agree to add threshold for inference, do we want to add `latency/token` threshold to mark test success or failed?

for training, we didn't find training in ReadME yet, so we don't have training for LLaMA2 in this PR, or we mean training for other models?

For `using benchmark results to define the right threshold values`, sure, will do

**Comment by ManfeiBai** [comment]
> @ManfeiBai wdyt we submit a follow up PR for GPU testing as well? (after this work successfully lands)

sure, we have GPU test on XL-ML-dashboard already, let's add LLaMA2 on GPU test too

**Comment by miladm** [comment]
Bunch of [comments](https://github.com/GoogleCloudPlatform/ml-testing-accelerators/commit/315f2e7f0c268bc92575fc26690b4970e2366021#commitcomment-124806347) - for the record

**Comment by ManfeiBai** [comment]
local test failed with `ModuleNotFoundError: No module named 'torch.distributed._functional_collectives'`

**Comment by ManfeiBai** [comment]
tested locally and output expected

**Comment by ManfeiBai** [comment]
> Thanks @ManfeiBai
> 
> We need a metric to detect regressions. For inference, we can define a `latency/token` threshold that we know is reachable. For training, we can define a MFU threshold.
> 
> Let's use our benchmark results to define the right threshold values. Wdyt?

will try to `latency/token` for inference accoridng to https://github.com/pytorch-tpu/llama/pull/35 or calculate directly

**Comment by ManfeiBai** [comment]
> @ManfeiBai wdyt we submit a follow up PR for GPU testing as well? (after this work successfully lands)

will create new PRs for GPU tests

**Comment by ManfeiBai** [comment]
will ad threshold in the follow up PRs

**Comment by ManfeiBai** [comment]
has added `latency/token` as a threshold for inference

**Review by miladm — APPROVED** [review]
I don't see the inference latency threshold and train thresholds. Will that be a follow up PR?

we need to push this change asap. Though, it seems we will need a follow up PR that would target more accurate thresholds, different model sizes, on GPU and TPU. Let's push this in for now. Thank you. @wonjoolee95 to take a second look as well.

**Comment by ManfeiBai** [comment]
> I don't see the inference latency threshold and train thresholds. Will that be a follow up PR?
> 
> we need to push this change asap. Though, it seems we will need a follow up PR that would target more accurate thresholds, different model sizes, on GPU and TPU. Let's push this in for now. Thank you. @wonjoolee95 to take a second look as well.

yes, we have threshold for inference and will have a followup PR for threshold of training

will merge this PR now

**Pull request merged**
