### PR TITLE
Fix `accelerate` version requirement in pt-nightly-hf-mlm-bert-b-fine-conv-v3-8-1vm.

### PR DESCRIPTION
**Pull request by vanbasten23**
# Description

This PR is intended to fix test pt-nightly-hf-mlm-bert-b-fine-conv-v3-8-1vm.

Today it failed with error:
```
+ python3 examples/pytorch/xla_spawn.py --num_cores 8 examples/pytorch/language-modeling/run_mlm.py --logging_dir ./tensorboard-metrics --cache_dir ./cache_dir --dataset_name wikitext --dataset_config_name wikitext-2-raw-v1 --do_train --do_eval --overwrite_output_dir --output_dir language-modeling --logging_steps 30 --save_steps 3000 --overwrite_cache --tpu_metrics_debug --model_type=bert --model_name_or_path bert-base-cased --num_train_epochs 3 --per_device_train_batch_size 16 --per_device_eval_batch_size 16

Exception in device=TPU:0: Using the `Trainer` with `PyTorch` requires `accelerate>=0.19.0`: Please run `pip install transformers[torch]` or `pip install accelerate -U`
```

This PR will fix this error.

# Tests

Please describe the tests that you ran on TPUs to verify changes.

**Instruction and/or command lines to reproduce your tests:**
```
$ TEST_NAME=pt-nightly-hf-mlm-bert-b-fine-conv-v3-8-1vm
$ gcloud container clusters get-credentials oneshots-us-central1 --region us-central1 --project xl-ml-test
$ jsonnet tests/oneshot.jsonnet -J . -S --tla-str test=$TEST_NAME | kubectl create -f -
```

**List links for your tests (use go/shortn-gen for any internal link):** 

[test](https://pantheon.corp.google.com/kubernetes/job/us-central1/oneshots-us-central1/default/pt-nightly-hf-mlm-bert-b-fine-conv-v3-8-1vm-c44c6/logs?e=13803378&jsmode=o&mods=allow_workbench_image_override&project=xl-ml-test)

Note, with this fix, there's a new error:
```
gsutil -m cp -r './tensorboard-metrics/*' gs://xl-ml-test-us-central1/output/pt-nightly/hf-mlm-bert-b-fine/conv/v3-8/pt-nightly-hf-mlm-bert-b-fine-conv-v3-8-1vm-c44c6
CommandException: No URLs matched: ./tensorboard-metrics/*
```
It seems the `--logging-dir` is not generated somehow.

Plan is to get this PR merged to fix the first error and then I'll continue look into the second one.

# Checklist

Before submitting this PR, please make sure (put X in square brackets):
- [x] I have performed a self-review of my code.
- [x] I have necessary comments in my code, particularly in hard-to-understand areas.
- [x] I have run one-shot tests and provided workload links above if applicable. 
- [x] I have made or will make corresponding changes to the doc if needed.

### CODE REVIEW

**Comment by will-cromar** [comment]
Please try rebasing this PR once https://github.com/GoogleCloudPlatform/ml-testing-accelerators/pull/918 merges and kick off the test again.

**Comment by vanbasten23** [comment]
rebased and I'm rerunning the test.

**Comment by vanbasten23** [comment]
Now it fails with a new error:
```
"Traceback (most recent call last):
  File "/home/xl-ml-test/.local/lib/python3.10/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 316, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/home/xl-ml-test/.local/lib/python3.10/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 310, in _start_fn
    fn(gindex, *args)
  File "/home/xl-ml-test/transformers/examples/pytorch/language-modeling/run_mlm.py", line 654, in _mp_fn
    main()
  File "/home/xl-ml-test/transformers/examples/pytorch/language-modeling/run_mlm.py", line 607, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/xl-ml-test/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1536, in train
    return inner_training_loop(
  File "/home/xl-ml-test/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1859, in _inner_training_loop
    xm.optimizer_step(self.optimizer)
  File "/home/xl-ml-test/.local/lib/python3.10/site-packages/torch_xla/core/xla_model.py", line 931, in optimizer_step
    reduce_gradients(optimizer, groups=groups, pin_layout=pin_layout)
  File "/home/xl-ml-test/.local/lib/python3.10/site-packages/torch_xla/core/xla_model.py", line 893, in reduce_gradients
    gradients = _fetch_gradients(optimizer)
  File "/home/xl-ml-test/.local/lib/python3.10/site-packages/torch_xla/core/xla_model.py", line 433, in _fetch_gradients
    for param_group in optimizer.__getstate__()['param_groups']:
KeyError: 'param_groups'"
```

**Comment by vanbasten23** [comment]
v3 doesn't have capacity, trying v4:
https://pantheon.corp.google.com/kubernetes/job/us-central1/oneshots-us-central1/default/pt-nightly-hf-mlm-bert-b-fine-conv-v4-8-1vm-npblf/details?e=13803378&jsmode=o&mods=allow_workbench_image_override&project=xl-ml-test

**Review by JackCaoG — APPROVED** [review]

**Review by will-cromar — APPROVED** [review]

**Comment by vanbasten23** [comment]
Thanks for the review!

**Pull request merged**
