### PR TITLE
Use torch-xla-1.7 conda env for the 1.7 mnist TPU pod test.

### PR DESCRIPTION
**Pull request by zcain117**
I'll wait to submit this until we get the torch-xla-1.7 conda env working

### CODE REVIEW

**Review by will-cromar — CHANGES_REQUESTED** [review]
Remember to also update the CONDA_ENV environment variable.

https://github.com/GoogleCloudPlatform/ml-testing-accelerators/blob/master/images/pytorch-pods/entrypoint.sh#L38

**Comment by zcain117** [comment]
> Remember to also update the CONDA_ENV environment variable.
> 
> https://github.com/GoogleCloudPlatform/ml-testing-accelerators/blob/master/images/pytorch-pods/entrypoint.sh#L38

Oh good point. Where does that get set?

**Comment by will-cromar** [comment]
You can override this field: https://github.com/GoogleCloudPlatform/ml-testing-accelerators/blob/master/tests/pytorch/common.libsonnet#L128

**Comment by zcain117** [comment]
Made the changes and it looks good, thanks for the advice Will!

[v3-32 run](https://pantheon.corp.google.com/logs/viewer?interval=PT1H&organizationId=433637338589&project=xl-ml-test&minLogLevel=0&expandAll=false&timestamp=2020-10-28T23:25:19.601000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22xl-ml-test%22%0Aresource.labels.location%3D%22europe-west4%22%0Aresource.labels.cluster_name%3D%22xl-ml-test-europe-west4%22%0Aresource.labels.namespace_name%3D%22automated%22%0Aresource.labels.pod_name%3D%22pt-r1.7-mnist-conv-v3-32-manual-6v5g5-z262l%22%0Aresource.labels.container_name%3D%22train%22&scrollTimestamp=2020-10-28T23:25:00.858471687Z&dateRangeUnbound=forwardInTime&dateRangeStart=2020-10-28T22:25:09.563Z)
[v2-32 run](https://pantheon.corp.google.com/logs/viewer?interval=PT1H&organizationId=433637338589&project=xl-ml-test&minLogLevel=0&expandAll=false&timestamp=2020-10-28T23:25:24.994000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22xl-ml-test%22%0Aresource.labels.location%3D%22europe-west4%22%0Aresource.labels.cluster_name%3D%22xl-ml-test-europe-west4%22%0Aresource.labels.namespace_name%3D%22automated%22%0Aresource.labels.pod_name%3D%22pt-r1.7-mnist-conv-v2-32-manual-2fwqq-68v6k%22%0Aresource.labels.container_name%3D%22train%22&dateRangeStart=2020-10-28T22:25:25.253Z&dateRangeEnd=2020-10-28T23:25:25.253Z&scrollTimestamp=2020-10-28T23:25:01.886928914Z)

**Review by will-cromar — APPROVED** [review]

**Pull request merged**
