### PR TITLE
Use directpath for GCS in resnet.

### PR DESCRIPTION
**Pull request by michaelbanfield**

### CODE REVIEW

**Review by will-cromar — CHANGES_REQUESTED** [review]
Can you move this override inside of `resnet`?

e.g. here: https://github.com/GoogleCloudPlatform/ml-testing-accelerators/blob/7b4b68546c1adb32ef718f52f4fef7feee946ecb/tests/tensorflow/nightly/resnet-ctl.libsonnet#L23

**Comment by michaelbanfield** [comment]
> Can you move this override inside of `resnet`?
> 
> e.g. here:
> 
> https://github.com/GoogleCloudPlatform/ml-testing-accelerators/blob/7b4b68546c1adb32ef718f52f4fef7feee946ecb/tests/tensorflow/nightly/resnet-ctl.libsonnet#L23

Done

**Comment by will-cromar** [comment]
Thanks. Before you submit, can you generate the Kubernetes resources by running `scripts/gen-tests.sh`? (Sorry, I'm hoping to automate this soon)

**Comment by michaelbanfield** [comment]
> Thanks. Before you submit, can you generate the Kubernetes resources by running `scripts/gen-tests.sh`? (Sorry, I'm hoping to automate this soon)

Done.

**Review by will-cromar — APPROVED** [review]
LGTM.

nit: can you revert all of these files with decimal rounding changes before you submit? I'm not sure what's going on there.

**Review by will-cromar — APPROVED** [review]
LGTM

**Pull request merged**
