### PR TITLE
Use memory-map for DLRM 2VM convergence test.

### PR DESCRIPTION
**Pull request by zcain117**
Trying to run this version now as `pt-nightly-dlrm-convergence-conv-v3-8-manual-m8ckj`

I'll make sure the job starts up and looks reasonable before submitting

### CODE REVIEW

**Review by taylanbil — APPROVED** [review]
What size vm is this test using?

**Comment by zcain117** [comment]
> What size vm is this test using?

64 CPU cores and 500GB memory

**Comment by zcain117** [comment]
Running now as `pt-nightly-dlrm-convergence-conv-v3-8-manual-bn2pc`, Will make sure it succeeds before submitting

**Review by taylanbil — APPROVED** [review]
lgtm, approving now but let's wait for test to pass.

**Comment by zcain117** [comment]
Test looks good: [logs](https://pantheon.corp.google.com/logs/viewer?interval=PT1H&project=xl-ml-test&minLogLevel=0&expandAll=false&timestamp=2021-03-23T00:01:12.805000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22xl-ml-test%22%0Aresource.labels.location%3D%22us-central1%22%0Aresource.labels.cluster_name%3D%22xl-ml-test-us-central1%22%0Aresource.labels.namespace_name%3D%22automated%22%0Aresource.labels.pod_name%3D%22pt-nightly-dlrm-convergence-conv-v3-8-manual-bn2pc-wd269%22%0Aresource.labels.container_name%3D%22train%22&scrollTimestamp=2021-03-22T20:37:44.415206004Z&dateRangeUnbound=both&dateRangeEnd=2021-03-23T00:01:10.595Z)

**Pull request merged**
