### PR TITLE
Updated the fairseq-cli to use hydra-config file

### PR DESCRIPTION
**Pull request by ultrons**
fairseq-cli in it's current form does not support mask related options.
However these options are supported via config file.
Updated the test to use config file.

### CODE REVIEW

**Comment by ultrons** [comment]
> 

@will-cromar is the original test passing now?
My understanding was that these updates would still be required or we are not running this test? 
Please confirm.

**Comment by will-cromar** [comment]
Reopening because this test is still broken

**Comment by miaoshasha** [comment]
testing this change

**Comment by JackCaoG** [comment]
@will-cromar Can we merge this change? I think I fixed the w2v2 so with this change it should start running. If it failed again I will take another pass.

**Review by will-cromar — APPROVED** [review]

**Pull request merged**
