### PR TITLE
[pt-2.1 | LLaMA2] Clean installation in LLaMA2 model with common and add threshold for training

### PR DESCRIPTION
**Pull request by ManfeiBai**
# Description

Clean installation in LLaMA2 model with common and add threshold

# Tests

Please describe the tests that you ran on TPUs to verify changes.

**Instruction and/or command lines to reproduce your tests:** ...
./scripts/run-oneshot.sh -t pt-2.1-llama2-pjrt-train-spmd-func-v4-8-1vm-1vm
./scripts/run-oneshot.sh -t pt-2.1-llama2-pjrt-infer-func-v4-8-1vm-1vm
./scripts/run-oneshot.sh -t pt-2.1-llama2-pjrt-train-spmd2b-conv-func-v4-8-1vm-1vm
./scripts/run-oneshot.sh -t pt-2.1-llama2-pjrt-infer70b-func-v4-8-1vm-1vm
./scripts/run-oneshot.sh -t pt-2.1-llama2-pjrt-train-spmd2b-128-func-v4-8-1vm-1vm

# Checklist

Before submitting this PR, please make sure (put X in square brackets):
- [x] I have performed a self-review of my code.
- [x] I have necessary comments in my code, particularly in hard-to-understand areas.
- [x] I have run one-shot tests and provided workload links above if applicable. 
- [x] I have made or will make corresponding changes to the doc if needed.

### CODE REVIEW

**Review by wonjoolee95 — APPROVED** [review]

**Review by will-cromar — APPROVED** [review]
Thanks!

**Review by alanwaketan — COMMENTED** [review]
The batch size seems too small. Can we set it to 128? --per_device_train_batch_size

**Comment by ManfeiBai** [comment]
> The batch size seems too small. Can we set it to 128? --per_device_train_batch_size

`--per_device_train_batch_size 128` failed with OOM of `pt-2.1-llama2-pjrt-train-spmd-func-v4-8-1vm-1vm`: http://shortn/_67okdughLa

**Comment by alanwaketan** [comment]
> > The batch size seems too small. Can we set it to 128? --per_device_train_batch_size
> 
> `--per_device_train_batch_size 128` failed with OOM of `pt-2.1-llama2-pjrt-train-spmd-func-v4-8-1vm-1vm`: http://shortn/_67okdughLa

Can you re-test it with the pin update?

**Comment by ManfeiBai** [comment]
> > > The batch size seems too small. Can we set it to 128? --per_device_train_batch_size
> > 
> > 
> > `--per_device_train_batch_size 128` failed with OOM of `pt-2.1-llama2-pjrt-train-spmd-func-v4-8-1vm-1vm`: http://shortn/_67okdughLa
> 
> Can you re-test it with the pin update?

will retest again with the newest RC5 wheel

**Comment by alanwaketan** [comment]
> > > > The batch size seems too small. Can we set it to 128? --per_device_train_batch_size
> > > 
> > > 
> > > `--per_device_train_batch_size 128` failed with OOM of `pt-2.1-llama2-pjrt-train-spmd-func-v4-8-1vm-1vm`: http://shortn/_67okdughLa
> > 
> > 
> > Can you re-test it with the pin update?
> 
> will retest again with the newest RC5 wheel

Let's wait until https://github.com/pytorch/xla/pull/5592 is merged.

**Comment by ManfeiBai** [comment]
passed local llama2 training used 2B with `--per_device_train_batch_size 128` after tested with latest RC5 wheel with https://github.com/pytorch/xla/pull/5592

**Comment by ManfeiBai** [comment]
> > > > > The batch size seems too small. Can we set it to 128? --per_device_train_batch_size
> > > > 
> > > > 
> > > > `--per_device_train_batch_size 128` failed with OOM of `pt-2.1-llama2-pjrt-train-spmd-func-v4-8-1vm-1vm`: http://shortn/_67okdughLa
> > > 
> > > 
> > > Can you re-test it with the pin update?
> > 
> > 
> > will retest again with the newest RC5 wheel
> 
> Let's wait until [pytorch/xla#5592](https://github.com/pytorch/xla/pull/5592) is merged.

passed local llama2 training used 2B with `--per_device_train_batch_size 128` after tested with latest RC5 wheel with https://github.com/pytorch/xla/pull/5592

**Pull request merged**
