### PR TITLE
Merge TPU VM test branch

### PR DESCRIPTION
**Pull request by will-cromar**
@zcain117 FYI

- Add TPU VM tests
- Show diff summary in `diff` GitHub Action
- Remove automatic deployment of v1 metrics handler since TPU VM tests only use v2 metrics.

### CODE REVIEW

**Comment by zcain117** [comment]
@googlebot I consent.

**Comment by will-cromar** [comment]
@sshahrokhi

Please see https://github.com/GoogleCloudPlatform/ml-testing-accelerators/pull/416#issuecomment-849819749

**Comment by sshahrokhi** [comment]
@googlebot I consent.

**Comment by will-cromar** [comment]
[Test run](https://pantheon.corp.google.com/logs/viewer?advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22xl-ml-test%22%0Aresource.labels.location%3D%22us-central1%22%0Aresource.labels.cluster_name%3D%22xl-ml-test-us-central1%22%0Aresource.labels.namespace_name%3D%22default%22%0Aresource.labels.pod_name%3D%22tf-nightly-mnist-conv-v2-8-1vm-cw7xc%22%20severity%3E%3DDEFAULT&project=xl-ml-test)

**Review by zcain117 — APPROVED** [review]

**Pull request merged**
